---
fail_fast: false
default_language_version:
    python: python3.10
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
    - repo: https://github.com/executablebooks/mdformat
      rev: 0.7.17
      hooks:
          - id: mdformat
            additional_dependencies:
                - mdformat-gfm
                - mdformat-black
    - repo: https://github.com/cheshirekow/cmake-format-precommit
      rev: v0.6.13
      hooks:
          - id: cmake-format
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.6
      hooks:
          - id: shellcheck
            args: [--severity=error]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.9.0
      hooks:
          - id: mypy
            language: system
    - repo: https://github.com/psf/black
      rev: 24.2.0
      hooks:
          - id: black
            args: [--line-length=100]
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            name: isort (python)
    - repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
          - id: flake8
    - repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.3.5
      hooks:
          # - id: clang-tidy # No easy way to install clang-tidy on macOS
          # - id: oclint # oclint uses dylds that were not verified by macOS
          # - id: uncrustify # seems conflicts with clang-format
          # - id: cppcheck # No cppcheck on RedHat Linux
          - id: cpplint
          # - id: include-what-you-use # Cannot handle including files from external frameworks
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v17.0.6
      hooks:
          - id: clang-format
            args: [--style=Google, -i]
